# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import floyd_pb2 as floyd__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in floyd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FloydServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComputeShortestPaths = channel.unary_unary(
                '/floyd.FloydService/ComputeShortestPaths',
                request_serializer=floyd__pb2.GraphRequest.SerializeToString,
                response_deserializer=floyd__pb2.GraphResponse.FromString,
                _registered_method=True)
        self.GetComputeStatus = channel.unary_unary(
                '/floyd.FloydService/GetComputeStatus',
                request_serializer=floyd__pb2.StatusRequest.SerializeToString,
                response_deserializer=floyd__pb2.StatusResponse.FromString,
                _registered_method=True)


class FloydServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComputeShortestPaths(self, request, context):
        """计算图的最短路径
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComputeStatus(self, request, context):
        """获取计算状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FloydServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComputeShortestPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeShortestPaths,
                    request_deserializer=floyd__pb2.GraphRequest.FromString,
                    response_serializer=floyd__pb2.GraphResponse.SerializeToString,
            ),
            'GetComputeStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComputeStatus,
                    request_deserializer=floyd__pb2.StatusRequest.FromString,
                    response_serializer=floyd__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'floyd.FloydService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('floyd.FloydService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FloydService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComputeShortestPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/floyd.FloydService/ComputeShortestPaths',
            floyd__pb2.GraphRequest.SerializeToString,
            floyd__pb2.GraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComputeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/floyd.FloydService/GetComputeStatus',
            floyd__pb2.StatusRequest.SerializeToString,
            floyd__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
