# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: floyd.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'floyd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66loyd.proto\x12\x05\x66loyd\"W\n\x0cGraphRequest\x12\x14\n\x0cnum_vertices\x18\x01 \x01(\x05\x12\x1a\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x0b.floyd.Edge\x12\x15\n\rnum_processes\x18\x03 \x01(\x05\"5\n\x04\x45\x64ge\x12\x11\n\tfrom_node\x18\x01 \x01(\x05\x12\n\n\x02to\x18\x02 \x01(\x05\x12\x0e\n\x06weight\x18\x03 \x01(\x01\"\x88\x01\n\rGraphResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12#\n\x0f\x64istance_matrix\x18\x03 \x03(\x0b\x32\n.floyd.Row\x12\x18\n\x10\x63omputation_time\x18\x04 \x01(\x01\x12\x16\n\x0eprocesses_used\x18\x05 \x01(\x05\"\x18\n\x03Row\x12\x11\n\tdistances\x18\x01 \x03(\x01\"#\n\rStatusRequest\x12\x12\n\ncompute_id\x18\x01 \x01(\t\"C\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08progress\x18\x02 \x01(\x01\x12\x0f\n\x07message\x18\x03 \x01(\t2\x92\x01\n\x0c\x46loydService\x12\x41\n\x14\x43omputeShortestPaths\x12\x13.floyd.GraphRequest\x1a\x14.floyd.GraphResponse\x12?\n\x10GetComputeStatus\x12\x14.floyd.StatusRequest\x1a\x15.floyd.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'floyd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPHREQUEST']._serialized_start=22
  _globals['_GRAPHREQUEST']._serialized_end=109
  _globals['_EDGE']._serialized_start=111
  _globals['_EDGE']._serialized_end=164
  _globals['_GRAPHRESPONSE']._serialized_start=167
  _globals['_GRAPHRESPONSE']._serialized_end=303
  _globals['_ROW']._serialized_start=305
  _globals['_ROW']._serialized_end=329
  _globals['_STATUSREQUEST']._serialized_start=331
  _globals['_STATUSREQUEST']._serialized_end=366
  _globals['_STATUSRESPONSE']._serialized_start=368
  _globals['_STATUSRESPONSE']._serialized_end=435
  _globals['_FLOYDSERVICE']._serialized_start=438
  _globals['_FLOYDSERVICE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
